export const DASHBOARD_LAYOUT = {
  sidebarWidth: "w-64",
  mainOffset: "ml-64",
  headerHeight: "min-h-16",
  pagePadding: "p-8",
  pageMaxWidth: "max-w-7xl",
  pageGap: "space-y-6",
} as const;

export const DASHBOARD_TYPOGRAPHY = {
  sectionLabel: "text-xs font-bold tracking-widest uppercase text-slate-500 dark:text-slate-400",
  pageTitle: "text-3xl font-bold text-on-surface tracking-tight",
  pageSubtitle: "text-sm text-slate-600 dark:text-slate-400 font-medium leading-6",
  cardTitle: "text-base font-semibold text-on-surface",
  body: "text-sm text-on-surface-variant leading-6",
  meta: "text-xs text-slate-500 dark:text-slate-400",
} as const;

export const DASHBOARD_SURFACES = {
  card: "bg-surface-container-lowest dark:bg-gray-800 border border-outline-variant/30 dark:border-gray-700 rounded-xl shadow-sm",
  panel: "bg-surface-container-lowest dark:bg-gray-800 border border-outline-variant/25 dark:border-gray-700 rounded-xl shadow-sm",
  mutedPanel: "bg-surface-container-low dark:bg-gray-800/50 border border-outline-variant/20 dark:border-gray-700/50 rounded-xl",
} as const;

export const DASHBOARD_FORMS = {
  label: "block text-xs font-bold text-on-surface-variant mb-1",
  control: "w-full p-2.5 bg-surface-container-low dark:bg-gray-800 border border-outline-variant/30 dark:border-gray-700 rounded-lg text-sm text-on-surface focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-colors",
  select: "w-full p-2.5 bg-surface-container-low dark:bg-gray-800 border border-outline-variant/30 dark:border-gray-700 rounded-lg text-sm text-on-surface focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-colors appearance-none",
  alertError: "mb-4 p-3 bg-error-container/60 dark:bg-red-900/30 text-on-error-container dark:text-red-200 rounded-lg flex items-center gap-2 text-sm border border-error/20 dark:border-red-800",
  alertSuccess: "mb-4 p-3 bg-tertiary-fixed/30 dark:bg-green-900/30 text-on-tertiary-fixed-variant dark:text-green-200 rounded-lg flex items-center gap-2 text-sm border border-tertiary-fixed-dim/40 dark:border-green-800",
  primaryButton: "px-6 py-2.5 bg-primary text-on-primary rounded-xl text-sm font-bold hover:bg-primary/90 transition-colors disabled:opacity-70 shadow-sm",
} as const;

export const DASHBOARD_ACTIONS = {
  backLink: "inline-flex items-center gap-1 rounded-lg bg-surface-container-low dark:bg-gray-800 px-2 py-1 text-sm font-bold text-on-surface-variant hover:bg-surface-container dark:hover:bg-gray-700 hover:text-on-surface transition-colors",
  secondaryButton: "inline-flex items-center gap-2 rounded-xl border border-outline-variant/30 dark:border-gray-700 px-4 py-2 text-sm font-bold text-on-surface hover:bg-surface-container-low dark:hover:bg-gray-800 transition-colors",
  inverseButton: "inline-flex items-center gap-2 rounded-xl bg-inverse-surface dark:bg-gray-200 px-4 py-2 text-sm font-bold text-inverse-on-surface dark:text-gray-900 hover:bg-inverse-surface/90 dark:hover:bg-gray-300 transition-colors",
  primaryButton: "inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-on-primary hover:bg-primary/90 transition-colors disabled:opacity-70 shadow-sm",
  iconButton: "p-2 rounded-lg bg-surface-container-low dark:bg-gray-800 text-on-surface-variant hover:bg-surface-container dark:hover:bg-gray-700 hover:text-on-surface transition-all border border-outline-variant/25 dark:border-gray-700",
  iconButtonPrimary: "p-2 rounded-lg bg-primary/10 dark:bg-primary/20 text-primary hover:bg-primary hover:text-on-primary transition-all border border-primary/15 dark:border-primary/30",
  iconButtonDanger: "p-2 rounded-lg bg-error-container/60 dark:bg-red-900/30 text-error dark:text-red-400 hover:bg-error hover:text-on-error transition-all border border-error/20 dark:border-red-800",
  icon: "w-4 h-4",
  pageTitle: "text-2xl font-bold text-on-surface",
  pageSubtitle: "text-sm text-on-surface-variant mt-0.5",
} as const;

export const DASHBOARD_MODAL = {
  backdrop: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 print:hidden",
  dialog: "bg-surface-container-lowest rounded-xl shadow-2xl w-full max-w-lg max-h-[90vh] overflow-auto border border-outline-variant/25",
  dialogWide: "bg-surface-container-lowest rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto flex flex-col border border-outline-variant/25",
  header: "flex items-center justify-between p-4 border-b border-outline-variant/20",
  title: "font-bold text-on-surface flex items-center gap-2",
  titleIcon: "w-4 h-4 text-primary",
  closeButton: "text-on-surface-variant hover:text-on-surface transition-colors rounded-lg p-1 hover:bg-surface-container-low",
  content: "p-4",
} as const;

export const DASHBOARD_LIST = {
  shell: `${DASHBOARD_SURFACES.panel} overflow-hidden`,
  toolbar: "p-4 border-b border-outline-variant/20 flex justify-between items-center gap-4 bg-surface-container-low/50",
  searchWrapper: "relative w-72",
  searchIcon: "absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant",
  searchInput: "pl-10 pr-4 py-2 font-medium shadow-sm",
  tableScroll: "overflow-x-auto",
  table: "w-full text-left border-collapse",
  headRow: "bg-surface-container-lowest text-on-surface-variant uppercase text-[10px] font-black tracking-widest border-b border-outline-variant/20",
  headerCell: "px-6 py-4",
  headerCellRight: "px-6 py-4 text-right",
  body: "divide-y divide-outline-variant/15",
  empty: "p-8 text-center text-sm font-bold text-on-surface-variant",
  row: "hover:bg-surface-container-low/60 transition-colors group",
  cell: "px-6 py-5",
  cellRight: "px-6 py-5 text-right",
  avatar: "w-10 h-10 rounded-full bg-primary/10 text-primary flex items-center justify-center font-black text-lg shadow-sm",
  primaryText: "font-bold text-on-surface leading-tight",
  secondaryText: "text-xs text-on-surface-variant font-medium",
  badge: "inline-flex items-center px-2.5 py-1 rounded-lg bg-surface-container-low text-on-surface-variant text-[10px] font-black border border-outline-variant/30 uppercase tracking-widest",
  mutedText: "text-xs font-medium text-on-surface-variant",
  scoreIcon: "w-4 h-4 text-secondary fill-secondary",
  typeLabel: "text-[10px] font-bold text-on-surface-variant uppercase tracking-wider",
  balanceDueValue: "text-sm font-black text-error",
  balanceDueLabel: "text-[10px] font-bold text-error/70 uppercase",
  balanceCreditValue: "text-sm font-black text-tertiary",
  balanceCreditLabel: "text-[10px] font-bold text-tertiary/70 uppercase",
  balanceNeutralValue: "text-sm font-black text-on-surface",
  balanceNeutralLabel: "text-[10px] font-bold text-on-surface-variant uppercase",
  actionGroup: "flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity",
} as const;

export const DASHBOARD_INSIGHT_RAIL = {
  layout: "flex flex-col lg:flex-row gap-8",
  content: "flex-1",
  rail: "w-full lg:w-96 shrink-0 space-y-6",
  heroCard: "bg-primary-container text-on-primary p-6 rounded-xl ambient-shadow relative overflow-hidden",
  heroEyebrow: "text-[10px] font-black uppercase tracking-widest opacity-80 border-b border-on-primary/30 pb-1",
  heroTitle: "text-2xl font-black tracking-tight leading-none mb-2",
  heroText: "text-xs font-medium opacity-80 leading-relaxed max-w-[200px]",
  statGrid: "grid grid-cols-2 gap-4",
  statCard: `${DASHBOARD_SURFACES.panel} p-5 flex flex-col justify-between`,
  statLabel: "text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mb-1",
  statValue: "text-2xl font-black text-on-surface leading-tight",
  statValueDanger: "text-2xl font-black text-error leading-tight",
  statMeta: "mt-4 flex items-center gap-1 text-[10px] font-bold text-on-surface-variant uppercase",
  activityCard: `${DASHBOARD_SURFACES.panel} p-6`,
  activityTitle: "text-sm font-bold text-on-surface mb-6 flex items-center gap-2 border-b border-outline-variant/20 pb-3",
  activityTitleIcon: "material-symbols-outlined text-sm text-primary",
  activityTimeline: "space-y-6 relative before:content-[''] before:absolute before:left-3 before:top-2 before:bottom-2 before:w-[2px] before:bg-surface-container-high",
  activityItem: "relative pl-8",
  activityDot: "absolute left-0 top-1 w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center z-10",
  activityDotIcon: "material-symbols-outlined text-xs text-primary",
  activityName: "text-xs font-black text-on-surface leading-none mb-1",
  activityMeta: "text-[10px] font-bold text-on-surface-variant uppercase tracking-widest",
} as const;

export const DASHBOARD_CHROME = {
  sidebarShell: `${DASHBOARD_LAYOUT.sidebarWidth} h-screen fixed left-0 top-0 z-50 flex flex-col overflow-y-auto border-r border-outline-variant/20 bg-surface-container-low/85 py-4`,
  sidebarBrand: "px-6 mb-6 flex items-center space-x-3 shrink-0",
  sidebarLogo: "w-10 h-10 bg-primary-container rounded-lg flex items-center justify-center overflow-hidden shrink-0",
  sidebarBrandTitle: "text-lg font-black text-on-surface leading-tight truncate",
  sidebarBrandSubtitle: "text-xs uppercase tracking-widest text-on-surface-variant font-bold truncate",
  sidebarNav: "flex-1 px-2 space-y-0.5",
  sidebarGroup: "mb-2",
  sidebarGroupLabel: "px-4 pt-3 pb-1 text-xs font-bold uppercase tracking-widest text-on-surface-variant/70 select-none",
  sidebarItem: "flex items-center px-4 py-2.5 rounded-lg mx-1 transition-all",
  sidebarItemActive: "bg-primary/10 text-primary font-semibold translate-x-1",
  sidebarItemIdle: "text-on-surface-variant hover:bg-surface-container-lowest/70 hover:text-on-surface hover:translate-x-1",
  sidebarFooter: "shrink-0 mt-2 px-4 pb-2",
  sidebarUpgradeCard: "block bg-primary-container p-4 rounded-xl text-white mb-3 group hover:shadow-lg transition-all",
  sidebarFooterLink: "flex items-center px-3 py-2 text-on-surface-variant text-sm hover:text-primary transition-colors rounded-lg hover:bg-surface-container-lowest/60",
  sidebarFooterDanger: "flex items-center w-full px-3 py-2 text-on-surface-variant text-sm hover:text-error transition-colors rounded-lg hover:bg-surface-container-lowest/60",
  headerShell: `w-full sticky top-0 z-40 ${DASHBOARD_LAYOUT.headerHeight} bg-surface-container-lowest/85 backdrop-blur-md px-8 py-4 flex justify-between items-center ambient-shadow border-b border-outline-variant/10`,
  headerQuickLink: "text-sm transition-colors pb-1",
  headerQuickLinkActive: "text-primary font-semibold border-b-2 border-primary",
  headerQuickLinkIdle: "text-on-surface-variant font-medium hover:text-primary",
  headerIconLink: "p-2 text-on-surface-variant hover:bg-surface-container-low rounded-full transition-colors",
  headerAvatar: "w-10 h-10 rounded-full bg-primary/10 text-primary font-bold flex items-center justify-center text-sm mr-3 ring-2 ring-primary/10",
  headerMeta: "text-xs text-on-surface-variant font-medium",
  pageActions: "flex space-x-3 flex-shrink-0",
  pageFooter: "w-full mt-auto bg-surface-container-lowest border-t border-outline-variant/20",
  pageFooterInner: "flex flex-col md:flex-row justify-between items-center px-8 py-8 w-full max-w-7xl mx-auto",
  pageFooterBrandBlock: "mb-4 md:mb-0",
  pageFooterBrand: "text-sm font-bold text-on-surface mb-1",
  pageFooterMeta: "text-xs font-normal text-on-surface-variant",
  pageFooterLinks: "flex space-x-6",
  pageFooterLink: "text-xs font-normal text-on-surface-variant hover:text-primary transition-opacity",
  pageErrorShell: "flex flex-col items-center justify-center p-12 text-center h-[50vh]",
  pageErrorMessage: "text-on-surface-variant mt-2",
} as const;

export const DASHBOARD_WORKSPACE_NAV = {
  compactShell: "flex gap-2 overflow-x-auto rounded-xl border border-outline-variant/30 bg-surface-container-lowest p-2 shadow-sm",
  cardsShell: "grid grid-cols-1 gap-2 rounded-xl border border-outline-variant/30 bg-surface-container-lowest p-2 shadow-sm",
  compactItem: "inline-flex min-h-11 shrink-0 items-center gap-2 rounded-lg px-3.5 py-2 text-sm font-black transition-colors",
  cardItem: "flex min-h-20 items-start gap-3 rounded-lg px-3 py-3 transition-colors",
  itemIdle: "text-on-surface-variant hover:bg-surface-container-low hover:text-on-surface",
  iconIdle: "text-on-surface-variant/70",
  description: "mt-1 block text-xs font-medium leading-4 text-on-surface-variant",
  tones: {
    amber: {
      active: "bg-amber-50 text-amber-800 ring-1 ring-amber-200 dark:bg-amber-500/15 dark:text-amber-100 dark:ring-amber-400/25",
      activeIcon: "text-amber-600 dark:text-amber-200",
    },
    blue: {
      active: "bg-blue-50 text-blue-800 ring-1 ring-blue-200 dark:bg-blue-500/15 dark:text-blue-100 dark:ring-blue-400/25",
      activeIcon: "text-blue-600 dark:text-blue-200",
    },
    cyan: {
      active: "bg-cyan-50 text-cyan-800 ring-1 ring-cyan-200 dark:bg-cyan-500/15 dark:text-cyan-100 dark:ring-cyan-400/25",
      activeIcon: "text-cyan-600 dark:text-cyan-200",
    },
    emerald: {
      active: "bg-emerald-50 text-emerald-800 ring-1 ring-emerald-200 dark:bg-emerald-500/15 dark:text-emerald-100 dark:ring-emerald-400/25",
      activeIcon: "text-emerald-600 dark:text-emerald-200",
    },
    violet: {
      active: "bg-violet-50 text-violet-800 ring-1 ring-violet-200 dark:bg-violet-500/15 dark:text-violet-100 dark:ring-violet-400/25",
      activeIcon: "text-violet-600 dark:text-violet-200",
    },
  },
} as const;

export type DashboardStatusTone = "neutral" | "info" | "warning" | "success" | "danger";

export const DASHBOARD_STATUS_BADGES = {
  base: "inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-sm font-bold",
  tones: {
    neutral: "bg-surface-container-low text-on-surface-variant border-outline-variant/30",
    info: "bg-primary/10 text-primary border-primary/20",
    warning: "bg-secondary-container/20 text-on-secondary-container border-secondary-container/40",
    success: "bg-tertiary-fixed/30 text-on-tertiary-fixed-variant border-tertiary-fixed-dim/40",
    danger: "bg-error-container/60 text-on-error-container border-error/25",
  },
} as const;

export const DASHBOARD_DETAIL = {
  infoGrid: "grid grid-cols-1 md:grid-cols-2 gap-6",
  financeInfoGrid: "grid grid-cols-1 md:grid-cols-3 gap-6",
  infoCard: `${DASHBOARD_SURFACES.panel} p-5 space-y-2`,
  infoCardWide: `${DASHBOARD_SURFACES.panel} p-5 space-y-3 md:col-span-2`,
  infoCardStack: `${DASHBOARD_SURFACES.panel} p-5 flex flex-col gap-3`,
  profileHeader: `${DASHBOARD_SURFACES.panel} p-5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4`,
  profileIdentity: "flex items-center gap-4",
  profileAvatar: "w-12 h-12 rounded-full bg-primary/10 text-primary flex items-center justify-center shrink-0",
  profileIcon: "w-6 h-6",
  profileTitle: "text-xl font-bold text-on-surface",
  profileMeta: "text-xs font-bold text-on-surface-variant uppercase tracking-widest mt-0.5",
  infoRowsGrid: "grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm",
  infoRow: "flex items-start gap-2",
  infoRowIcon: "text-on-surface-variant/70 mt-0.5 shrink-0",
  infoRowLabel: "text-xs text-on-surface-variant font-medium",
  infoRowValue: "text-sm font-medium text-on-surface",
  financeMetricGroup: "space-y-3",
  financeMetricRow: "flex justify-between items-center gap-4",
  financeMetricLabel: "text-sm text-on-surface-variant",
  financeMetricValue: "text-base font-bold text-on-surface",
  financeMetricValueDanger: "text-lg font-bold font-mono text-error",
  financeMetricValueSuccess: "text-lg font-bold font-mono text-tertiary",
  actionCluster: "flex items-center gap-3 bg-surface-container-low p-2.5 rounded-xl border border-outline-variant/25",
  infoValue: "font-bold text-on-surface",
  infoValueLarge: "font-medium text-lg text-on-surface mt-2",
  infoPlate: "font-bold text-2xl text-primary mt-2",
  infoMeta: "text-sm text-on-surface-variant",
  infoMetaStack: "text-sm text-on-surface-variant space-y-1 mt-1 font-mono",
  infoCustomerNote: "text-xs text-secondary bg-secondary-container/20 border border-secondary-container/30 p-1.5 mt-2 rounded inline-block",
  relatedBlock: "mt-3 pt-3 border-t border-outline-variant/20",
  relatedLabel: "text-xs text-on-surface-variant font-bold uppercase tracking-widest mb-1 flex items-center gap-1",
  relatedLink: "text-sm font-bold text-primary hover:underline",
  sectionTitle: "text-xs font-bold text-on-surface-variant uppercase tracking-widest border-b border-outline-variant/20 pb-2",
  sectionTitleRow: "text-xs font-bold text-on-surface-variant uppercase tracking-widest border-b border-outline-variant/20 pb-2 flex items-center gap-2",
  notePanel: "bg-surface-container-low border border-outline-variant/25 p-4 rounded-lg relative",
  notePanelAccent: "bg-primary/10 border border-primary/20 p-4 rounded-lg relative flex flex-col pb-6",
  noteLabel: "absolute -top-3 left-4 bg-inverse-surface text-inverse-on-surface text-[10px] uppercase font-bold px-2 py-0.5 rounded-full",
  noteLabelAccent: "absolute -top-3 left-4 bg-primary text-on-primary text-[10px] uppercase font-bold px-2 py-0.5 rounded-full",
  noteText: "text-sm text-on-surface-variant mt-1 leading-relaxed",
  noteTextAccent: "text-sm text-primary mt-1 leading-relaxed",
  tableShell: `${DASHBOARD_SURFACES.panel} overflow-hidden`,
  tableToolbar: "bg-surface-container-low px-5 py-4 border-b border-outline-variant/20",
  tableToolbarRow: "flex items-center gap-2 px-5 py-4 border-b border-outline-variant/20 bg-surface-container-low",
  tableToolbarSplit: "bg-surface-container-low p-5 flex flex-col sm:flex-row justify-between items-center border-b border-outline-variant/20",
  tableTitle: "text-sm font-bold text-on-surface-variant uppercase tracking-widest",
  tableTitleLarge: "text-lg font-bold text-on-surface flex items-center gap-2",
  tableTitleIcon: "w-5 h-5 text-on-surface-variant",
  tableCount: "ml-auto text-xs font-bold text-on-surface-variant/70",
  tableHead: "bg-surface-container-lowest border-b border-outline-variant/20 text-on-surface-variant text-xs uppercase tracking-wider",
  tableBody: "divide-y divide-outline-variant/15 bg-surface-container-lowest",
  tableHeaderCell: "px-5 py-3 text-left",
  tableHeaderCellRight: "px-5 py-3 text-right",
  tableHeaderCellWide: "px-6 py-4",
  tableHeaderCellWideRight: "px-6 py-4 text-right",
  tableRow: "hover:bg-surface-container-low/60 transition-colors",
  tableCell: "px-5 py-3",
  tableCellRight: "px-5 py-3 text-right",
  tableCellWide: "px-6 py-4",
  tableCellWideRight: "px-6 py-4 text-right",
  tableCellPrimary: "font-medium text-on-surface",
  tableCellStrong: "font-bold text-on-surface",
  tableCellMuted: "text-on-surface-variant",
  tableCellMutedSmall: "text-on-surface-variant text-xs",
  tableCellDanger: "text-error text-xs font-bold",
  tableCellMeta: "text-xs text-on-surface-variant/70 mt-1 uppercase tracking-wider font-semibold",
  tableCellMoney: "font-mono font-medium text-on-surface-variant",
  tableCellMoneyStrong: "font-bold text-on-surface text-base font-mono",
  tableEmpty: "px-5 py-10 text-center text-on-surface-variant",
  tableEmptyWide: "px-6 py-12 text-center text-on-surface-variant",
  tableEmptyIcon: "w-8 h-8 mx-auto text-on-surface-variant/40 mb-2",
  itemAccent: {
    part: "bg-primary",
    labor: "bg-tertiary",
  },
  tableSummary: "bg-surface-container-low border-t border-outline-variant/20 p-5 flex flex-col items-end gap-1 text-sm",
  tableSummaryWide: "bg-surface-container-low border-t border-outline-variant/20 p-6 flex flex-col items-end gap-2 text-sm text-right",
  financeSummaryBody: "space-y-2 text-sm",
  financeSummaryRow: "flex justify-between text-on-surface-variant",
  financeSummaryDiscountRow: "flex justify-between text-error",
  financeSummaryPaidRow: "flex justify-between text-tertiary",
  financeSummaryTotalRow: "flex justify-between font-bold text-base border-t border-outline-variant/30 pt-2 mt-2 text-on-surface",
  financeSummaryBalanceDueRow: "flex justify-between font-bold text-lg border-t border-outline-variant/30 pt-2 mt-2 text-error",
  financeSummaryBalancePaidRow: "flex justify-between font-bold text-lg border-t border-outline-variant/30 pt-2 mt-2 text-tertiary",
  paymentList: "divide-y divide-outline-variant/20",
  paymentRow: "flex items-center justify-between px-5 py-3.5",
  paymentIcon: "w-8 h-8 rounded-full bg-tertiary-fixed/30 flex items-center justify-center shrink-0",
  paymentIconGlyph: "w-4 h-4 text-on-tertiary-fixed-variant",
  linkList: "divide-y divide-outline-variant/15",
  linkListRow: "flex items-center justify-between px-5 py-3.5 hover:bg-surface-container-low/60 transition-colors group",
  linkListPrimary: "font-bold text-primary text-base font-mono",
  linkListMeta: "text-sm text-on-surface-variant",
  linkListAction: "text-xs text-on-surface-variant/70 group-hover:text-primary transition-colors",
  summaryRow: "flex justify-between w-full max-w-xs text-on-surface-variant",
  summaryTotalRow: "flex justify-between w-full max-w-xs font-bold text-lg border-t border-outline-variant/30 pt-2 mt-1",
  summaryRowWide: "w-full max-w-sm flex justify-between py-1 text-on-surface-variant",
  summaryRowWideOffset: "w-full max-w-sm flex justify-between py-1 text-on-surface-variant pt-2",
  summaryDiscountRowWide: "w-full max-w-sm flex justify-between py-1 text-error border-b border-outline-variant/30 border-dashed pb-2",
  summaryTotalRowWide: "w-full max-w-sm flex justify-between py-3 mt-2 text-2xl font-bold text-on-surface border-t border-outline-variant/40",
} as const;

export function dashboardStatusBadgeClass(
  tone: DashboardStatusTone,
  className = ""
) {
  return [
    DASHBOARD_STATUS_BADGES.base,
    DASHBOARD_STATUS_BADGES.tones[tone],
    className,
  ]
    .filter(Boolean)
    .join(" ");
}

export function dashboardPageContainerClass(className = "") {
  return [
    DASHBOARD_LAYOUT.pagePadding,
    DASHBOARD_LAYOUT.pageGap,
    DASHBOARD_LAYOUT.pageMaxWidth,
    "mx-auto w-full",
    className,
  ]
    .filter(Boolean)
    .join(" ");
}
